[workspace]
resolver = "2"
members = [
    "projects/gaia-frontend",
]
default-members = [
    "projects/gaia-frontend",
]
exclude = [
    "projects/.DS_Store",
    "projects/gaia-frontend-wasm32",
]

[workspace.dependencies]
gaia-types = { path = "../project-gaia/projects/gaia-types" }

[profile.release]
lto = true
panic = "abort"
